/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.user;

import controllers.user.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import static java.awt.image.ImageObserver.HEIGHT;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author macbookpro
 */
public class DienDonSuDungNhaVanHoaViews extends javax.swing.JFrame {

    private String hours[] = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"};
    private String minutes[] = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
        "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51",
        "52", "53", "54", "55", "56", "57", "58", "59"};
    final DefaultComboBoxModel modelHours1 = new DefaultComboBoxModel(hours);
    final DefaultComboBoxModel modelHours2 = new DefaultComboBoxModel(hours);
    final DefaultComboBoxModel modelMinutes1 = new DefaultComboBoxModel(minutes);
    final DefaultComboBoxModel modelMinutes2 = new DefaultComboBoxModel(minutes);

    /**
     * Creates new form DienDonSuDungNhaVanHoaViews
     */
    public DienDonSuDungNhaVanHoaViews() {        
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();        
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        confirmButton = new javax.swing.JButton();
        roomComboBox = new javax.swing.JComboBox<>();
        jDateStart = new com.toedter.calendar.JDateChooser();
        hourBoxStart = new javax.swing.JComboBox<>();
        minuteBoxStart = new javax.swing.JComboBox<>();
        jDateFinish = new com.toedter.calendar.JDateChooser();
        hourBoxFinish = new javax.swing.JComboBox<>();
        minuteBoxFinish = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(852, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VUI LÒNG ĐIỀN THÔNG TIN SAU");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 4));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 400, 53);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BẮT ĐẦU TỪ");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(78, 159, 80, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HẠN ĐẾN");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(78, 236, 80, 44);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NỘI DUNG");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(78, 316, 80, 80);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PHÒNG");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(78, 96, 80, 45);

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("(*)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(758, 159, 50, 44);

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("(*)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(491, 96, 43, 44);

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("(*)");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(758, 348, 37, 44);

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        description.setColumns(20);
        description.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(176, 316, 572, 85);

        confirmButton.setBackground(new java.awt.Color(102, 0, 153));
        confirmButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmButton.setText("GỬI BIỂU MẪU");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton);
        confirmButton.setBounds(349, 418, 174, 46);

        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new DienDonSuDungNhaVanHoa().layDanhSachPhong()));
        roomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(roomComboBox);
        roomComboBox.setBounds(176, 96, 311, 44);

        jDateStart.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(jDateStart);
        jDateStart.setBounds(551, 159, 197, 44);

        hourBoxStart.setModel(modelHours1);
        hourBoxStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourBoxStartActionPerformed(evt);
            }
        });
        getContentPane().add(hourBoxStart);
        hourBoxStart.setBounds(176, 159, 94, 44);

        minuteBoxStart.setModel(modelMinutes2);
        minuteBoxStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        minuteBoxStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minuteBoxStartActionPerformed(evt);
            }
        });
        getContentPane().add(minuteBoxStart);
        minuteBoxStart.setBounds(340, 159, 91, 44);

        jDateFinish.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(jDateFinish);
        jDateFinish.setBounds(551, 236, 197, 44);

        hourBoxFinish.setModel(modelHours2);
        hourBoxFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourBoxFinishActionPerformed(evt);
            }
        });
        getContentPane().add(hourBoxFinish);
        hourBoxFinish.setBounds(176, 236, 94, 44);

        minuteBoxFinish.setModel(modelMinutes1);
        getContentPane().add(minuteBoxFinish);
        minuteBoxFinish.setBounds(339, 237, 90, 43);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Giờ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 200, 50, 44);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Phút");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 210, 40, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Giờ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 270, 60, 44);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Phút");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(360, 270, 50, 44);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Ngày");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(493, 159, 60, 44);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ngày");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(497, 237, 60, 43);

        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("(*)");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(758, 236, 42, 44);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 820, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed

        // L?y v? th?i gian b?t d?u s? ki?n c?a y�u c?u.
        
        try {
            Date dateStart = jDateStart.getDate();
            if (dateStart == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập hết các trường bắt buộc", "Alert", HEIGHT);
            }
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String startTimeRequest = dateFormat.format(dateStart) + " " + hourBoxStart.getSelectedIndex() + ":" + minuteBoxStart.getSelectedIndex() + ":00";
            Date dateFinish = jDateFinish.getDate();
            if (dateFinish == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập hết các trường bắt buộc", "Alert", HEIGHT);
            }
            String finishTimeRequest = dateFormat.format(dateFinish) + " " + hourBoxFinish.getSelectedIndex() + ":" + minuteBoxFinish.getSelectedIndex() + ":00";

            String userUsername;
            String requestDescriptions;
            String requestRoom;
            userUsername = new CurrentUserUsername().getCurrentUserUsrename();
            requestDescriptions = description.getText();
            requestRoom = roomComboBox.getItemAt(roomComboBox.getSelectedIndex());
            if (requestDescriptions.isEmpty()
                    || startTimeRequest.equals(null)
                    || finishTimeRequest.equals(null)
                    || requestRoom.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập hết các trường bắt buộc", "Alert", HEIGHT);
            } else {
//            System.out.println(userUsername);
                if (new DienDonSuDungNhaVanHoa().themDonYeuCau(userUsername, startTimeRequest, finishTimeRequest, requestDescriptions, requestRoom)) {
                    JOptionPane.showMessageDialog(this, "Yêu cầu được thêm vào hệ thống");
                } else {
                    JOptionPane.showMessageDialog(this, "�? c� l?i x?y ra. Vui l?ng th? l?i");
                };
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_confirmButtonActionPerformed

    private void roomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomComboBoxActionPerformed

    private void hourBoxStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourBoxStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourBoxStartActionPerformed

    private void hourBoxFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourBoxFinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourBoxFinishActionPerformed

    private void minuteBoxStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuteBoxStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minuteBoxStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void hienThi() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DienDonSuDungNhaVanHoaViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DienDonSuDungNhaVanHoaViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DienDonSuDungNhaVanHoaViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DienDonSuDungNhaVanHoaViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DienDonSuDungNhaVanHoaViews().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextArea description;
    private javax.swing.JComboBox<String> hourBoxFinish;
    private javax.swing.JComboBox<String> hourBoxStart;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateFinish;
    private com.toedter.calendar.JDateChooser jDateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> minuteBoxFinish;
    private javax.swing.JComboBox<String> minuteBoxStart;
    private javax.swing.JComboBox<String> roomComboBox;
    // End of variables declaration//GEN-END:variables
}
