package views.mng;

import controllers.ThongKePanelController;
import javax.swing.JFrame;



public class ThongKePanel extends javax.swing.JPanel {
    private JFrame parentFrame;
    private ThongKePanelController controller;
    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        this.controller = new ThongKePanelController(GenderJcb, StatusJcb, tuTuoiJtf, denTuoiJtf, tableJpn);
        this.controller.setDataTable();
        this.controller.setData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderChoose = new javax.swing.ButtonGroup();
        statusChoose = new javax.swing.ButtonGroup();
        tableJpn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tuTuoiJtf = new javax.swing.JTextField();
        denTuoiJtf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        GenderJcb = new javax.swing.JComboBox<>();
        StatusJcb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        add(tableJpn);
        tableJpn.setBounds(283, 0, 770, 612);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tình trạng:");
        add(jLabel1);
        jLabel1.setBounds(10, 113, 87, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Độ tuổi từ:");
        add(jLabel2);
        jLabel2.setBounds(10, 63, 86, 30);

        tuTuoiJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tuTuoiJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuTuoiJtfActionPerformed(evt);
            }
        });
        add(tuTuoiJtf);
        tuTuoiJtf.setBounds(114, 65, 51, 30);

        denTuoiJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(denTuoiJtf);
        denTuoiJtf.setBounds(213, 65, 51, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("=>");
        add(jLabel4);
        jLabel4.setBounds(183, 63, 20, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(1057, 110, 0, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Giới tính:");
        add(jLabel7);
        jLabel7.setBounds(10, 11, 75, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Thống kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(82, 161, 102, 29);

        GenderJcb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GenderJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Nam", "Nữ" }));
        GenderJcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderJcbActionPerformed(evt);
            }
        });
        add(GenderJcb);
        GenderJcb.setBounds(114, 11, 150, 30);

        StatusJcb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        StatusJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Thường trú", "Tạm trú", "Tạm vắng", "Khai tử" }));
        add(StatusJcb);
        StatusJcb.setBounds(115, 113, 150, 30);

        jLabel3.setText("Biểu đồ thống kê giới tính và độ tuổi");
        add(jLabel3);
        jLabel3.setBounds(60, 280, 190, 50);

        jButton2.setText("Giới tính");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(30, 360, 110, 40);

        jButton3.setText("Độ tuổi");
        add(jButton3);
        jButton3.setBounds(160, 360, 120, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.controller.setData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GenderJcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderJcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderJcbActionPerformed

    private void tuTuoiJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuTuoiJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuTuoiJtfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderChoose;
    private javax.swing.JComboBox<String> GenderJcb;
    private javax.swing.JComboBox<String> StatusJcb;
    private javax.swing.JTextField denTuoiJtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.ButtonGroup statusChoose;
    private javax.swing.JPanel tableJpn;
    private javax.swing.JTextField tuTuoiJtf;
    // End of variables declaration//GEN-END:variables
}
