/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.mng;

import controllers.mng.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JScrollPane;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ThongTinCoSoVatChat;
import models.TinhTrangYeuCau;
import services.MysqlConnection;

/**
 *
 * @author keplegarry
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        jComboBoxVatPhamUpdate();
        XemLichSuDung();
        XemThongTinDangKy();
    }
    
    private void XemLichSuDung(){
        DefaultTableModel model = (DefaultTableModel) jTableLich.getModel();
        XemLich.show(model);
    }
    
    private void XemThongTinDangKy(){
        DefaultTableModel model = (DefaultTableModel) jTableDonDangKy.getModel();
        ThongTinNguoiDungDangKy.print(model);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelTop = new javax.swing.JLabel();
        jPanelLeft = new javax.swing.JPanel();
        jPanelTrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelQuanLyCSVC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelLich = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelDonDangKy = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelDangXuat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelCentre = new javax.swing.JPanel();
        jPanelTrangChuCentre = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanelLichCentre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLich = new javax.swing.JTable();
        jLabelTenSuKien = new javax.swing.JLabel();
        jLabelThoiGian = new javax.swing.JLabel();
        jLabelPhong = new javax.swing.JLabel();
        jLabelLoaiSuKien = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelMoTa = new javax.swing.JLabel();
        jButtonCapNhatDuLieu = new javax.swing.JButton();
        jPanelDonDangKyCentre = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDonDangKy = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanelQuanLyCSVCCentre = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCapNhatCSVC = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxVatPham = new javax.swing.JComboBox<>();
        jButtonChiTiet = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTTTenVatPham = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTTSoLuong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTTPhong = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldTT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldTTNgayCapNhat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxPhong = new javax.swing.JComboBox<>();
        jButtonCapNhat = new javax.swing.JButton();
        jPanelThemCSVC = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldTenVatPham1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSpinnerSoLuong1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldTT1 = new javax.swing.JTextField();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel21 = new javax.swing.JLabel();
        jButtonXacNhan1 = new javax.swing.JButton();
        jButtonLamMoi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sử dụng nhà văn hóa");

        jPanel.setLayout(new java.awt.BorderLayout());

        jPanelTop.setBackground(new java.awt.Color(102, 102, 102));

        jLabelTop.setText("Quản lý sử dụng nhà văn hóa");
        jLabelTop.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTop.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabelTop)
                .addGap(221, 221, 221))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelTop)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel.add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanelLeft.setBackground(new java.awt.Color(102, 102, 102));

        jPanelTrangChu.setBackground(new java.awt.Color(153, 153, 153));
        jPanelTrangChu.setPreferredSize(new java.awt.Dimension(185, 60));
        jPanelTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel1.setText("Trang Chủ");
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTrangChuLayout = new javax.swing.GroupLayout(jPanelTrangChu);
        jPanelTrangChu.setLayout(jPanelTrangChuLayout);
        jPanelTrangChuLayout.setHorizontalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrangChuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanelTrangChuLayout.setVerticalGroup(
            jPanelTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelQuanLyCSVC.setBackground(new java.awt.Color(153, 153, 153));
        jPanelQuanLyCSVC.setPreferredSize(new java.awt.Dimension(185, 60));
        jPanelQuanLyCSVC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel2.setText("Quản lý CSVC");
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelQuanLyCSVCLayout = new javax.swing.GroupLayout(jPanelQuanLyCSVC);
        jPanelQuanLyCSVC.setLayout(jPanelQuanLyCSVCLayout);
        jPanelQuanLyCSVCLayout.setHorizontalGroup(
            jPanelQuanLyCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyCSVCLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelQuanLyCSVCLayout.setVerticalGroup(
            jPanelQuanLyCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuanLyCSVCLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelLich.setBackground(new java.awt.Color(153, 153, 153));
        jPanelLich.setPreferredSize(new java.awt.Dimension(118, 60));
        jPanelLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel3.setText("Lịch");
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelLichLayout = new javax.swing.GroupLayout(jPanelLich);
        jPanelLich.setLayout(jPanelLichLayout);
        jPanelLichLayout.setHorizontalGroup(
            jPanelLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLichLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLichLayout.setVerticalGroup(
            jPanelLichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLichLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        jPanelDonDangKy.setBackground(new java.awt.Color(153, 153, 153));
        jPanelDonDangKy.setPreferredSize(new java.awt.Dimension(153, 60));
        jPanelDonDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel4.setText("Đơn đăng ký");
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDonDangKyLayout = new javax.swing.GroupLayout(jPanelDonDangKy);
        jPanelDonDangKy.setLayout(jPanelDonDangKyLayout);
        jPanelDonDangKyLayout.setHorizontalGroup(
            jPanelDonDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDonDangKyLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDonDangKyLayout.setVerticalGroup(
            jPanelDonDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDonDangKyLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );

        jPanelDangXuat.setBackground(new java.awt.Color(153, 153, 153));
        jPanelDangXuat.setPreferredSize(new java.awt.Dimension(151, 60));
        jPanelDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLeftMouseClickedEvt(evt);
            }
        });

        jLabel5.setText("Đăng xuất");
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelDangXuatLayout = new javax.swing.GroupLayout(jPanelDangXuat);
        jPanelDangXuat.setLayout(jPanelDangXuatLayout);
        jPanelDangXuatLayout.setHorizontalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDangXuatLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDangXuatLayout.setVerticalGroup(
            jPanelDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDangXuatLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelQuanLyCSVC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLich, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
            .addComponent(jPanelDonDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
            .addComponent(jPanelDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addComponent(jPanelTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelQuanLyCSVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDonDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jPanelDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel.add(jPanelLeft, java.awt.BorderLayout.LINE_START);

        jPanelCentre.setLayout(new java.awt.CardLayout());

        jPanelTrangChuCentre.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Thêm sự kiện");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrangChuCentreLayout = new javax.swing.GroupLayout(jPanelTrangChuCentre);
        jPanelTrangChuCentre.setLayout(jPanelTrangChuCentreLayout);
        jPanelTrangChuCentreLayout.setHorizontalGroup(
            jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrangChuCentreLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jButton1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanelTrangChuCentreLayout.setVerticalGroup(
            jPanelTrangChuCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrangChuCentreLayout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(83, 83, 83))
        );

        jPanelCentre.add(jPanelTrangChuCentre, "card2");

        jPanelLichCentre.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        jTableLich = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        jTableLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sự kiện", "T/g bắt đầu", "T/g kết thúc", "Phòng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableLich.setBackground(new java.awt.Color(204, 204, 204));
        jTableLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLichMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLich);

        jLabelTenSuKien.setText("Tên sự kiện:");

        jLabelThoiGian.setText("Thời gian:");

        jLabelPhong.setText("Phòng:");

        jLabelLoaiSuKien.setText("Loại sự kiện:");

        jLabelGia.setText("Giá:");

        jLabelMoTa.setText("Mô tả:");

        jButtonCapNhatDuLieu.setText("Cập nhật dữ liệu");
        jButtonCapNhatDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhatDuLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLichCentreLayout = new javax.swing.GroupLayout(jPanelLichCentre);
        jPanelLichCentre.setLayout(jPanelLichCentreLayout);
        jPanelLichCentreLayout.setHorizontalGroup(
            jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                .addGroup(jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMoTa)
                            .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                                .addGroup(jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPhong)
                                    .addComponent(jLabelTenSuKien))
                                .addGap(92, 92, 92)
                                .addGroup(jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelThoiGian)
                                    .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                                        .addComponent(jLabelLoaiSuKien)
                                        .addGap(185, 185, 185)
                                        .addComponent(jLabelGia))))))
                    .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jButtonCapNhatDuLieu)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanelLichCentreLayout.setVerticalGroup(
            jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLichCentreLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenSuKien)
                    .addComponent(jLabelThoiGian))
                .addGap(18, 18, 18)
                .addGroup(jPanelLichCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhong)
                    .addComponent(jLabelLoaiSuKien)
                    .addComponent(jLabelGia))
                .addGap(27, 27, 27)
                .addComponent(jLabelMoTa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButtonCapNhatDuLieu)
                .addContainerGap())
        );

        jPanelCentre.add(jPanelLichCentre, "card4");

        jTableDonDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tên người dùng", "T/g bắt đầu", "T/g kết thúc", "Phòng", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableDonDangKy.setCellSelectionEnabled(true);
        jTableDonDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDonDangKyMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableDonDangKy);

        jButton2.setText("Cập nhật");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDonDangKyCentreLayout = new javax.swing.GroupLayout(jPanelDonDangKyCentre);
        jPanelDonDangKyCentre.setLayout(jPanelDonDangKyCentreLayout);
        jPanelDonDangKyCentreLayout.setHorizontalGroup(
            jPanelDonDangKyCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
            .addGroup(jPanelDonDangKyCentreLayout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDonDangKyCentreLayout.setVerticalGroup(
            jPanelDonDangKyCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDonDangKyCentreLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanelCentre.add(jPanelDonDangKyCentre, "card5");

        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));

        jPanelCapNhatCSVC.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("Chọn vật phẩm:");
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonChiTiet.setText("Chi tiết");
        jButtonChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChiTietActionPerformed(evt);
            }
        });

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel11.setText("Tên vật phẩm:");

        jLabel12.setText("Số lượng:");

        jLabel13.setText("Phòng:");

        jLabel15.setText("Thông tin:");

        jLabel16.setText("Ngày cập nhật: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldTTTenVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTTPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTTSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTTNgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTT, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldTTTenVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldTTSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldTTPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldTTNgayCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jLabel10.setText("Thông tin");
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setText("Phòng:");

        jComboBoxPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hội trường", "Phòng chức năng 1" }));
        jComboBoxPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPhongActionPerformed(evt);
            }
        });

        jButtonCapNhat.setText("Cập nhật");
        jButtonCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCapNhatCSVCLayout = new javax.swing.GroupLayout(jPanelCapNhatCSVC);
        jPanelCapNhatCSVC.setLayout(jPanelCapNhatCSVCLayout);
        jPanelCapNhatCSVCLayout.setHorizontalGroup(
            jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jComboBoxPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
            .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButtonChiTiet)
                .addGap(113, 113, 113)
                .addComponent(jButtonCapNhat)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCapNhatCSVCLayout.setVerticalGroup(
            jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCapNhatCSVCLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVatPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelCapNhatCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChiTiet)
                    .addComponent(jButtonCapNhat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab(" Cập nhật cơ sở vật chất", jPanelCapNhatCSVC);

        jPanelThemCSVC.setBackground(new java.awt.Color(204, 204, 204));

        jLabel17.setText("Chọn phòng:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hội trường", "Phòng chức năng 1" }));

        jLabel18.setText("Tên vật phẩm:");

        jLabel19.setText("Số lượng:");

        jLabel20.setText("Thông tin:");

        jLabel21.setText("Thời gian:");

        jButtonXacNhan1.setText("Xác nhận");
        jButtonXacNhan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhan1ActionPerformed(evt);
            }
        });

        jButtonLamMoi1.setText("Làm mới");
        jButtonLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLamMoi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelThemCSVCLayout = new javax.swing.GroupLayout(jPanelThemCSVC);
        jPanelThemCSVC.setLayout(jPanelThemCSVCLayout);
        jPanelThemCSVCLayout.setHorizontalGroup(
            jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(71, 71, 71)
                        .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 133, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTenVatPham1))
                                .addGap(88, 88, 88)
                                .addComponent(jLabel19)
                                .addGap(52, 52, 52)
                                .addComponent(jSpinnerSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtonXacNhan1)
                        .addGap(104, 104, 104)
                        .addComponent(jButtonLamMoi1)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanelThemCSVCLayout.setVerticalGroup(
            jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemCSVCLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldTenVatPham1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jSpinnerSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldTT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelThemCSVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXacNhan1)
                    .addComponent(jButtonLamMoi1))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Thêm cơ sở vật chất", jPanelThemCSVC);

        javax.swing.GroupLayout jPanelQuanLyCSVCCentreLayout = new javax.swing.GroupLayout(jPanelQuanLyCSVCCentre);
        jPanelQuanLyCSVCCentre.setLayout(jPanelQuanLyCSVCCentreLayout);
        jPanelQuanLyCSVCCentreLayout.setHorizontalGroup(
            jPanelQuanLyCSVCCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanelQuanLyCSVCCentreLayout.setVerticalGroup(
            jPanelQuanLyCSVCCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanelCentre.add(jPanelQuanLyCSVCCentre, "card5");

        jPanel.add(jPanelCentre, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelLeftMouseClickedEvt(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLeftMouseClickedEvt
        if(evt.getSource() == jPanelTrangChu){
            jPanelTrangChuCentre.setVisible(true);
            jPanelQuanLyCSVCCentre.setVisible(false);
            jPanelLichCentre.setVisible(false);
            jPanelDonDangKyCentre.setVisible(false);
        }
        if(evt.getSource() == jPanelQuanLyCSVC){
            jPanelTrangChuCentre.setVisible(false);
            jPanelQuanLyCSVCCentre.setVisible(true);
            jPanelLichCentre.setVisible(false);
            jPanelDonDangKyCentre.setVisible(false);
        }
        if(evt.getSource() == jPanelLich){
            jPanelTrangChuCentre.setVisible(false);
            jPanelQuanLyCSVCCentre.setVisible(false);
            jPanelLichCentre.setVisible(true);
            jPanelDonDangKyCentre.setVisible(false);
        }
        if(evt.getSource() == jPanelDonDangKy){
            jPanelTrangChuCentre.setVisible(false);
            jPanelQuanLyCSVCCentre.setVisible(false);
            jPanelLichCentre.setVisible(false);
//            JScrollPane donDangKy = new PheDuyetYeuCauNguoiDungViews().pheDuyetYeuCauNguoiDung();         
//            donDangKy.setSize(jPanelDonDangKyCentre.getSize());
//            jPanelDonDangKyCentre.add(donDangKy);
            jPanelDonDangKyCentre.setVisible(true);
        }
        if(evt.getSource() == jPanelDangXuat){
            if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.dispose();
                new LogInView().setVisible(true);
            } else {
               
            }
        }
    }//GEN-LAST:event_jPanelLeftMouseClickedEvt

    private void jButtonChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChiTietActionPerformed
        ThongTinCoSoVatChat tt = CapNhatCoSoVatChat.thongTinCoSoVatChat((String)jComboBoxVatPham.getSelectedItem(), (String)jComboBoxPhong.getSelectedItem());
        jTextFieldTTTenVatPham.setText(tt.getItemName());
        jTextFieldTT.setText(tt.getItemDescriptions());
        jTextFieldTTNgayCapNhat.setText(tt.getLastTimeUpDate()); 
        jTextFieldTTPhong.setText(tt.getRoomName());
        jTextFieldTTSoLuong.setText(tt.getAmount() + "");
    }//GEN-LAST:event_jButtonChiTietActionPerformed

    private void jComboBoxPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPhongActionPerformed

        jComboBoxVatPhamUpdate();
    }//GEN-LAST:event_jComboBoxPhongActionPerformed

    private void jButtonCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhatActionPerformed
        new CapNhatCoSoVatChatFrame().setVisible(true);
    }//GEN-LAST:event_jButtonCapNhatActionPerformed

    private void jButtonXacNhan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhan1ActionPerformed
        if(jTextFieldTenVatPham1.getText().length() == 0 || datePicker1.getDate() == null || jTextFieldTT1.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Vui vòng điền đẩy đủ thông tin", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if((int)jSpinnerSoLuong1.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Số lượng phải lớn hơn 0", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        CapNhatCoSoVatChat.themCSVC(jTextFieldTenVatPham1.getText(), (String)jComboBox1.getSelectedItem(), datePicker1.getDate().toString(), jTextFieldTT1.getText(), (int)jSpinnerSoLuong1.getValue());                   
        jComboBoxVatPhamUpdate();
    }//GEN-LAST:event_jButtonXacNhan1ActionPerformed

    private void jButtonLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLamMoi1ActionPerformed
        jTextFieldTT1.setText("");
        jTextFieldTenVatPham1.setText("");
        datePicker1.setDate(null);
        jSpinnerSoLuong1.setValue(0);
    }//GEN-LAST:event_jButtonLamMoi1ActionPerformed

    private void jTableLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLichMouseClicked
        ArrayList<String> arr = XemLich.showDetail((DefaultTableModel)jTableLich.getModel(), jTableLich.getSelectedRow());
        jLabelTenSuKien.setText("Tên sự kiện: " + arr.get(0));
        jLabelThoiGian.setText("Thời gian từ: " + arr.get(1) + " đến: " + arr.get(2));
        jLabelPhong.setText("Phòng: " + arr.get(3));
        jLabelLoaiSuKien.setText("Loại sự kiện: " + arr.get(4));
        jLabelMoTa.setText("Mô tả: " + arr.get(5));
        jLabelGia.setText("Chi Phí: " + arr.get(6) + " đ");
        
                
        
    }//GEN-LAST:event_jTableLichMouseClicked

    private void jButtonCapNhatDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCapNhatDuLieuActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableLich.getModel();
        model.setRowCount(0);
        XemLichSuDung();
    }//GEN-LAST:event_jButtonCapNhatDuLieuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ThemSuKienFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableDonDangKy.getModel();
        model.setRowCount(0);
        XemThongTinDangKy();;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableDonDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDonDangKyMouseClicked
        new ChapNhanYeuCau((DefaultTableModel) jTableDonDangKy.getModel(), jTableDonDangKy.getSelectedRow()).setVisible(true);
    }//GEN-LAST:event_jTableDonDangKyMouseClicked
    
    private void jComboBoxVatPhamUpdate(){
        jComboBoxVatPham.removeAllItems();
        try{
            Connection conn = MysqlConnection.getMysqlConnection();
            String phong = (String)jComboBoxPhong.getSelectedItem();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from Infrastructure");
             while(rs.next()){
                if(rs.getString("RoomName").equals(phong)){
                    jComboBoxVatPham.addItem(rs.getString("ItemName"));
                }
        }
        } catch(SQLException e){
            
        } catch(ClassNotFoundException e){
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCapNhat;
    private javax.swing.JButton jButtonCapNhatDuLieu;
    private javax.swing.JButton jButtonChiTiet;
    private javax.swing.JButton jButtonLamMoi1;
    private javax.swing.JButton jButtonXacNhan1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxPhong;
    private javax.swing.JComboBox<String> jComboBoxVatPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelLoaiSuKien;
    private javax.swing.JLabel jLabelMoTa;
    private javax.swing.JLabel jLabelPhong;
    private javax.swing.JLabel jLabelTenSuKien;
    private javax.swing.JLabel jLabelThoiGian;
    private javax.swing.JLabel jLabelTop;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCapNhatCSVC;
    private javax.swing.JPanel jPanelCentre;
    private javax.swing.JPanel jPanelDangXuat;
    private javax.swing.JPanel jPanelDonDangKy;
    private javax.swing.JPanel jPanelDonDangKyCentre;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelLich;
    private javax.swing.JPanel jPanelLichCentre;
    private javax.swing.JPanel jPanelQuanLyCSVC;
    private javax.swing.JPanel jPanelQuanLyCSVCCentre;
    private javax.swing.JPanel jPanelThemCSVC;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanelTrangChu;
    private javax.swing.JPanel jPanelTrangChuCentre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerSoLuong1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDonDangKy;
    private javax.swing.JTable jTableLich;
    private javax.swing.JTextField jTextFieldTT;
    private javax.swing.JTextField jTextFieldTT1;
    private javax.swing.JTextField jTextFieldTTNgayCapNhat;
    private javax.swing.JTextField jTextFieldTTPhong;
    private javax.swing.JTextField jTextFieldTTSoLuong;
    private javax.swing.JTextField jTextFieldTTTenVatPham;
    private javax.swing.JTextField jTextFieldTenVatPham1;
    // End of variables declaration//GEN-END:variables
}
